{% set name = "nionutils" %}
{% set version = "0.3.20" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a75d38e029012f007e4c52b49041ad67e113183724f409517dc6130e2fc6870f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: "https://github.com/nion-software/nionutils"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "Nion utility classes."
  dev_url: https://github.com/nion-software/nionutils

extra:
  recipe-maintainers:
    - cmeyer
    - ericpre
